name: Generate application
on:
  workflow_dispatch:
  push:
    paths:
      - '**.py'
permissions:
  contents: write
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: 'false'

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.5'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      - name: Generate program
        run: |
          pyinstaller -D --distpath .\dist\ -i .\logo.ico --contents-directory libraries --uac-admin -n "Fhoe-Rail" Honkai_Star_Rail.py -y

      - name: Move assets to dist directory
        run: |
          xcopy /E /I /Y .\map\ .\dist\Fhoe-Rail\map\
          xcopy /E /I /Y .\map_data\ .\dist\Fhoe-Rail\map_data\
          xcopy /E /I /Y .\picture\ .\dist\Fhoe-Rail\picture\
          xcopy /Y .\README.md .\dist\Fhoe-Rail\

      - name: Extract tag name
        if: startsWith(github.ref, 'refs/tags/')
        id: extract_tag
        run: echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"

      - name: Add version to version.json
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          $tag = "${{ steps.extract_tag.outputs.tag }}"
          $versionJson = Get-Content -Raw version.json | ConvertFrom-Json
          $versionJson.version = $tag
          $versionJson | ConvertTo-Json | Set-Content version.json

      - name: Upload artifact
        if: startsWith(github.ref, 'refs/heads/') || startsWith(github.ref, 'refs/pull/')
        uses: actions/upload-artifact@v3
        with:
          name: Fhoe-Rail
          path: .\dist\Fhoe-Rail\

      - name: Create zip archive
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          powershell Compress-Archive -Path .\dist\Fhoe-Rail\ -DestinationPath .\dist\Fhoe-Rail.zip -Force

      - name: Create release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
#          name: Fhoe-Rail
          files: |
           ./dist/Fhoe-Rail.zip
#          prerelease: true
